### ISSUE TITLE
Image viewer file support

### ISSUE THREAD

**Issue by Austinthemighty** [dmpop/little-backup-box#60]
I mainly take photos in raw, how would I be able to view them using the image viewer, I added the file type to the format array, but it only shows the missing image icon.  Is there a way to add support for the different images.

**Comment by dmpop** [comment]
Since the viewer is written in PHP, I don't think it's possible to add support for RAW files. But you can browse and view the RAW files on Little Backup Box using any Samba or UPnP client. Also, please post Little Backup Box-related questions on https://discuss.pixls.us/c/hardware/little-backup-box/
